### ISSUE TITLE
[Feature request] Add account switcher

### ISSUE THREAD

**Issue by VityaSchel** [session-foundation/session-android#351]
fuck it, close this if you want, but at least it will be saved in issues history.

Please add account switcher to app. Preferably with unlimited accounts, or at least not three as in telegram official client.

It would help user to protect its identity and be more anonymous when using separate accounts.

Technically, I don't see any problem here with moving private/pub keys to separate dirs for each account and global app settings to shared dir. I haven't looked at the android client code yet, so tell me if there is anything that prevents this feature from implementation other than code refactoring :)

Concepts:
Here are some concepts of ux that you could use.
1. User taps on profile picture, goes to settings screen. But there is a scroll view where pfp currently is. Like a roulette. you can scroll profile pictures horizontally and switch between accounts by doing this. This concept is taken from Yandex.mail mobile app. Last element is always plus sign (or any other icon) that indicates login initial screen where you get when you open app first time, like create new account or recover with phrase.
2. User can tap on profile picture and open settings. Or it can hold profile picture and see list of available accounts with profile pictures and usernames. It can switch account by tapping on any item or tap on last list item to add new account.
3. Or you can straight up steal UI from Telegram and move settings button to burger menu (left nav bar, I forgot how it's called in mobile dev :p). By tapping on profile picture, user opens this menu. In this menu user can see all accounts and some options like settings, about app, sign out. 

I wish I could help by writing some code, but I don't know Jaba vaba so I hope dev team will be able to implement this feature without pr

**Comment by FOSS-Enjoyer-715** [comment]
> Useful discussion but closing as duplicate of https://github.com/oxen-io/session-android-temp/issues/740

@KeeJef 

Since the duplicate issue is no longer available, could you guys reopen this issue please?
