### ISSUE TITLE
[BUG] session taking forever to do anything 

### ISSUE THREAD

**Issue by Gamerdude1634** [session-foundation/session-android#37]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever you send a pic or video to your friends or family members it takes forever to send and receive the message

**Comment by EmmaDoetPijpen** [comment]
> We're looking into this currently, since we have seen many reports of slower than average performance in Session iOS, Android and Desktop, especially when it comes to sending files. We're investigating the rollout of libQUIC, which is supported across all storage servers but only used by the iOS client to communicate instead of http, we think the higher usage of libQUIC might be causing some crashes on storage servers, which are impacting the rest of the network. Will have additional updates over the next week as we investigate

Any updates? I'm on the latest (1.16.5) and videos don't load at all. I can send videos and they receive them just fine, but if they send me videos they don't load. Text messages load fine. Tried reinstalling, turning off VPN, rebooting.

**Comment by KeeJef** [comment]
> Any updates? I'm on the latest (1.16.5) and videos don't load at all. I can send videos and they receive them just fine, but if they send me videos they don't load. Text messages load fine. Tried reinstalling, turning off VPN, rebooting.

There's an issue with media sent from iOS rendering properly on Session Desktop, should be a new release out for Desktop and iOS soon

**Comment by EmmaDoetPijpen** [comment]
Thanks for the quick reply! The sender is indeed using an iPhone. Looking
forward to the update! :-)

**Comment by KeeJef** [comment]
New Session Desktop version is out now, should fix the issue moving forward, however wont refresh old media which was stuck loading
