### ISSUE TITLE
you constantly monitoring what i typing? 

### ISSUE THREAD

**Issue by onlineapps-cloud** [session-foundation/session-android#825]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/session-foundation/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

question is, how you detect account seed phrase when i want to send it to someone? in my case i send it to myself, but how it's working?
i send to second account my seed phrase in this format: `"session: word1 word2 word3 ..."`
so my message starting with `"session:"` when i put message in text box i get this alert:
![image](https://github.com/user-attachments/assets/71c21197-13d7-4d5d-94d3-e8818ad81c63)
how it's technically working? you constantly monitoring clipboard from my seed phrase? if yes, how you parse only seed phrase from another text?. where in the code is located this function? i want to see how it's looking this code that made this action.
Very strange action made your software.
i think that seed phrase is stored in plain text on the phone, to verify this action, but i don't understand how did you made matching of my random text + seed phrase with local seed phrase.
best regards.

### Android Version

android 14

### Session Version

1.20.2

**Comment by KeeJef** [comment]
Explanation given here https://github.com/oxen-io/session-android/issues/1704, closing this for now
